### ISSUE TITLE
Publish new version on npm?

### ISSUE THREAD

**Issue by singingwolfboy** [TooTallNate/proxy#19]
It looks like the `args` dependency was updated from 3.0.2 to 5.0.1 in 2a29d92d812a01c9f574298f076ac975b15f4823. `args` 3.0.2 depends on `minimist` 1.2.0, which falls under a npm security advisory: see https://npmjs.com/advisories/1179

Because you've already updated the `args` dependency, this is no longer a problem for the latest version of the code, but it appears that the latest version is not yet published on npm. Could you please publish it, so others can update and stop using this old version of `minimist`?

**Comment by arantes555** [comment]
I would love to see a new version published too.

**Comment by tex0l** [comment]
The project in which I use `proxy` will undergo an independent security review very soon, and I'd like the report to be as clean as possible.
This is my last `npm audit` warning, would it be possible to release the new version ASAP so that I can make it disappear @TooTallNate 🙏 ? I'd be very thankful.

**Comment by roaringUnicorn** [comment]
I would also like to have the last version published !

**Comment by TooTallNate** [comment]
Published v1.0.2
